name: Android Java Bindings CI
on: push

jobs:
  build-only-android:
    name: Build only (Android)
    runs-on: windows-latest
    timeout-minutes: 60
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: microsoft
          java-version: 11

      - name: Install .NET 6.0.x
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: "6.0.x"

      - name: Install .NET workloads
        run: dotnet workload install maui-android

      - name: Compile
        run: dotnet build -c Debug -v n SDL2-CS-Android
